name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}  
      
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@34.229.139.68 << 'EOF'
        cd /home/ubuntu/hello-world-app
        # Install pm2 if not already installed
          if ! command -v pm2 &> /dev/null
          then
            echo "pm2 not found, installing..."
            sudo npm install -g pm2
          else
            echo "pm2 is already installed"
          fi
        git pull origin main
        npm install
        npm run build
        pm2 start npm --name hello-world-app
        EOF
