name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          debug: true
          script: | 
            sudo apt update -y
            sudo apt install nodejs npm -y
            git clone git@github.com:wahid000786/nestjs-app.git
            cd hello-world-app
            npm install
            npm start > app.log 2>&1 &
            echo "Application Started"
