name: CI

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          username: ubuntu
          EC2_KEY: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/hello-world-app
            git checkout .
            git pull
            npm install
            npm run build
            pm2 restart 0
            exit
